# -*- coding: utf-8 -*-
"""DSCI303_Final_Kmeans_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U650pna9I4Kl2X2hQokQtXJmt4RTCtWj
"""

from google.colab import drive
drive.mount('/content/drive')



import pandas as pd
import numpy as np

path = "/content/drive/MyDrive/Junior Spring/DSCI303/Final Project/Final_Augmented_dataset_Diseases_and_Symptoms.csv"
df = pd.read_csv(path)

df.head()

df.shape

print("Shape:", df.shape)
print("Number of unique diseases:", df["diseases"].nunique())
print("\nFirst 10 columns:")
print(df.columns[:10].tolist())

print("\nHead:")
print(df.head())

print("\nMissing values:")
print(df.isnull().sum().sum())

import matplotlib.pyplot as plt
# ----------------------------
# 2. Basic overview
# ----------------------------
print("Shape of dataset:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

# ----------------------------
# 3. Identify label column
# ----------------------------
if "diseases" in df.columns:
    label_col = "diseases"
elif "Disease" in df.columns:
    label_col = "Disease"
else:
    label_col = df.columns[-1]   # assume last column is target

print("\nLabel column:", label_col)

# ----------------------------
# 4. Missing values
# ----------------------------
missing_per_col = df.isnull().sum()
total_missing = missing_per_col.sum()

print("\nTotal missing values in dataset:", total_missing)
print("\nColumns with missing values:")
print(missing_per_col[missing_per_col > 0].sort_values(ascending=False))

# ----------------------------
# 5. Duplicate rows
# ----------------------------
num_duplicates = df.duplicated().sum()
print("\nNumber of duplicate rows:", num_duplicates)

# ----------------------------
# 6. Target variable analysis
# ----------------------------
print("\nNumber of unique diseases:", df[label_col].nunique())

class_counts = df[label_col].value_counts()

print("\nTop 10 most common diseases:")
print(class_counts.head(10))

print("\nTop 10 least common diseases:")
print(class_counts.tail(10))

print("\nSummary of class counts:")
print(class_counts.describe())

# ----------------------------
# 7. Feature analysis
# ----------------------------
X = df.drop(columns=[label_col])

print("\nNumber of feature columns:", X.shape[1])

# number of unique values in each feature
unique_counts = X.nunique()

print("\nFeature unique-value summary:")
print(unique_counts.describe())

# check if features are mostly binary
non_binary_cols = [col for col in X.columns if not set(X[col].dropna().unique()).issubset({0, 1})]

print("\nNumber of non-binary feature columns:", len(non_binary_cols))
if len(non_binary_cols) > 0:
    print("Some non-binary columns:")
    print(non_binary_cols[:20])

# symptom frequency
symptom_counts = X.sum().sort_values(ascending=False)

print("\nTop 20 most frequent symptoms:")
print(symptom_counts.head(20))

print("\nTop 20 least frequent symptoms:")
print(symptom_counts.tail(20))

# ----------------------------
# 8. Rare classes
# ----------------------------
rare_classes = class_counts[class_counts < 2]
print("\nNumber of diseases with fewer than 2 samples:", len(rare_classes))

# optional
print("\nDiseases with fewer than 2 samples:")
print(rare_classes)

# ----------------------------
# 9. Quick plots
# ----------------------------

# class distribution
plt.figure(figsize=(10, 5))
class_counts.plot(kind="hist", bins=50)
plt.title("Distribution of Number of Samples per Disease")
plt.xlabel("Samples per Disease")
plt.ylabel("Number of Diseases")
plt.show()

# top 20 diseases
plt.figure(figsize=(12, 6))
class_counts.head(20).plot(kind="bar")
plt.title("Top 20 Most Common Diseases")
plt.xlabel("Disease")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.show()

# top 20 symptoms
plt.figure(figsize=(12, 6))
symptom_counts.head(20).plot(kind="bar")
plt.title("Top 20 Most Frequent Symptoms")
plt.xlabel("Symptom")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.show()

# ----------------------------
# 10. Useful summary prints
# ----------------------------
print("\nFinal EDA Summary")
print("------------------")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Features:", X.shape[1])
print("Unique diseases:", df[label_col].nunique())
print("Total missing values:", total_missing)
print("Duplicate rows:", num_duplicates)
print("Diseases with <2 samples:", len(rare_classes))
print("Non-binary feature columns:", len(non_binary_cols))

# Drop rows where label is missing
df_clean = df.dropna(subset=[label_col]).copy()

# Fill missing feature values with 0 (symptom absent)
df_clean = df_clean.fillna(0)

# Remove duplicates
df_clean = df_clean.drop_duplicates()

print("Final shape:", df_clean.shape)

from sklearn.preprocessing import LabelEncoder
y = df_clean[label_col]
class_counts = y.value_counts()
# Remove rare classes from dataset
valid_classes = class_counts[class_counts >= 10].index

df_clean = df_clean[df_clean[label_col].isin(valid_classes)].copy()

df_clean = df_clean.sample(n=100000, random_state=42)

# redo X, y after filtering
X = df_clean.drop(columns=[label_col])
y = df_clean[label_col]
y_encoded = LabelEncoder().fit_transform(y)



"""# Kmean"""

#reduce with PCA
from sklearn.decomposition import PCA

X = df_clean.drop(columns=[label_col])

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

from sklearn.cluster import KMeans


#kmeans clustering
k = 3
kmeans = KMeans(n_clusters=k, random_state=0)
y_predicted = kmeans.fit_predict(X_pca)

import matplotlib.pyplot as plt
centroids = kmeans.cluster_centers_
plt.figure(figsize=(7,6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_predicted)
plt.scatter(centroids[:, 0], centroids[:, 1],
            c='red',
            edgecolor='black', # Outline for visibility
            label='Centroids')
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("KMeans on PCA-reduced data")
plt.show()

import pandas as pd
import numpy as np

# 1. Get the centroids in PCA space
centroids_pca = kmeans.cluster_centers_

# 2. Inverse transform them back to the original feature space
# This gives us a 'profile' of the average symptom values for that cluster
centroids_original = pca.inverse_transform(centroids_pca)

# 3. Create a DataFrame for better readability
feature_names = X.columns
df_centroids = pd.DataFrame(centroids_original, columns=feature_names)

print("--- Characteristics of the 3 Cluster Centroids ---")
for i in range(k):
    print(f"\nCluster {i} Top Symptoms:")
    # Sort symptoms by their 'intensity' or frequency in the centroid
    top_symptoms = df_centroids.iloc[i].sort_values(ascending=False).head(5)
    print(top_symptoms)

# Sum the values for each cluster (row) across all symptom columns
avg_symptom_counts = df_centroids.sum(axis=1)

print("--- Average Number of Symptoms per Cluster ---")
for i, count in enumerate(avg_symptom_counts):
    print(f"Cluster {i}: {count:.2f} symptoms")

# Print the coordinates to match them with the plot
for i, center in enumerate(kmeans.cluster_centers_):
    print(f"Cluster {i} (from your 'Top Symptoms' list) is at PCA coordinates: {center}")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

scores = []

for k in range(2, 20):
    kmeans = KMeans(n_clusters=k, random_state=0)
    labels = kmeans.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores.append(score)
    print(f"k={k}, score={score}")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

scores = []

for k in range(700, 700):
    kmeans = KMeans(n_clusters=k, random_state=0)
    labels = kmeans.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    scores.append(score)
    print(f"k={k}, score={score}")

plt.scatter(range(2, 20), scores)
plt.plot(range(2, 20), scores)
plt.xlabel("Number of clusters")
plt.ylabel("Silhouette coefficient")
plt.title("Silhouette coefficient vs. # of clusters")



"""# Language model

"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet google-genai gitingest

import sys

# Additional authentication is required for Google Colab
if "google.colab" in sys.modules:
    # Authenticate user to Google Cloud
    from google.colab import auth

    auth.authenticate_user()

import os

from google import genai

# fmt: off
PROJECT_ID = "dsci303-test"  # @param {type: "string", placeholder: "[your-project-id]", isTemplate: true}

# fmt: on
if not PROJECT_ID or PROJECT_ID == "[your-project-id]":
    PROJECT_ID = str(os.environ.get("GOOGLE_CLOUD_PROJECT"))

LOCATION = os.environ.get("GOOGLE_CLOUD_REGION", "global")

client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)

import nest_asyncio
from IPython.display import Audio, Image, Markdown, Video, display
from gitingest import ingest
from google.genai.types import CreateCachedContentConfig, GenerateContentConfig, Part

nest_asyncio.apply()

MODEL_ID = "gemini-2.5-flash"  # @param {type: "string"}

import random
import json

# number of samples
N = 8

# sample rows
df_sample = df_clean.sample(n=N, random_state=0)

X_sample = df_sample.drop(columns=[label_col])
y_sample = df_sample[label_col].astype(str)

allowed_labels = sorted(df_clean[label_col].astype(str).unique())

def row_to_text(row):
    active = []
    for col, val in row.items():
        if val == 1:
            active.append(col)
        elif val not in (0, 1):
            active.append(f"{col}={val}")
    return ", ".join(active) if active else "No symptoms"

def build_prompt(symptoms):
    return f"""
Choose exactly ONE disease from this list:
{", ".join(allowed_labels)}

Symptoms:
{symptoms}

Return JSON:
{{"predicted_disease": "...", "reasoning": "..."}}
"""

correct = 0

for i, (idx, row) in enumerate(X_sample.iterrows()):
    symptoms = row_to_text(row)
    true_label = y_sample.loc[idx]

    prompt = build_prompt(symptoms)

    response = client.models.generate_content(
        model="gemini-3.1-pro-preview",  # or your model
        contents=prompt
    )

    text = response.text.strip()

    try:
        data = json.loads(text)
        pred = data.get("predicted_disease", "").strip()
        reasoning = data.get("reasoning", "")
    except:
        pred = "PARSE_ERROR"
        reasoning = text

    is_correct = (pred == true_label)
    if is_correct:
        correct += 1

    print(f"\nExample {i+1}")
    print("Symptoms:", symptoms[:200])
    print("True:", true_label)
    print("Pred:", pred)
    print("Correct:", is_correct)
    print("Reasoning:", reasoning[:150])

# final accuracy
print("\n======================")
print(f"Correct: {correct}/{N}")
print(f"Accuracy: {correct/N:.2f}")

